# Generated by Django 3.2.6 on 2021-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
