# Generated by Django 3.2.6 on 2021-08-24 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0002_auto_20210821_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
