# Generated by Django 3.2.6 on 2021-08-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0003_ranking_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
