# Generated by Django 3.2.5 on 2021-08-27 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0004_alter_ranking_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='correcta',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='incorrecta',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='pregunta',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
