# Generated by Django 3.2.6 on 2021-09-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0007_ranking_pregunta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='pregunta_id',
            new_name='pregunta_rel',
        ),
    ]
